sudo: false

notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.0"
  - "5.0"
env:
  - "FAKEREDIS=true"
  - "FAKEREDIS=false"
branches:
  only:
    - master
services:
  - redis-server
# before_script:
after_failure: 
  - "cat /home/travis/builds/taskrabbit/node-resque/npm-debug.log"
